repos:
  - repo: local
    hooks:
      - id: clang-format
        name: Formatter
        entry: bash -c 'clang-format -i "$@"; git add -u' --
        language: python
        files: \.c$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
